name: Deploy website
on:
  push:
    branches:
      - master
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}      
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Fly setup
        uses: superfly/flyctl-actions/setup-flyctl@master  
      - name: Deploy
        run: flyctl deploy --remote-only         